--==========================================================================================================================
-- CIVILIZATIONS
--==========================================================================================================================
-- Types
-------------------------------------	
INSERT INTO Types	
		(Type,								Kind)
VALUES	('CIVILIZATION_LEU_ARGENTINA',		'KIND_CIVILIZATION');
-------------------------------------			
-- Civilizations			
-------------------------------------				
-- Types
-------------------------------------	
INSERT INTO Civilizations	
		(CivilizationType,				Name,									Description,									Adjective,									StartingCivilizationLevelType,	RandomCityNameDepth,	Ethnicity)
VALUES	('CIVILIZATION_LEU_ARGENTINA',	'LOC_CIVILIZATION_LEU_ARGENTINA_NAME',	'LOC_CIVILIZATION_LEU_ARGENTINA_DESCRIPTION',	'LOC_CIVILIZATION_LEU_ARGENTINA_ADJECTIVE',	'CIVILIZATION_LEVEL_FULL_CIV',	10,						'ETHNICITY_SOUTHAM');	
-------------------------------------			
-- CityNames			
-------------------------------------		
INSERT INTO CityNames	
			(CivilizationType,					CityName)	
VALUES		('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITY_NAME_LEU_ARGENTINA_01'),
			('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITY_NAME_LEU_ARGENTINA_02'),
			('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITY_NAME_LEU_ARGENTINA_03'),
			('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITY_NAME_LEU_ARGENTINA_04'),
			('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITY_NAME_LEU_ARGENTINA_05'),
			('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITY_NAME_LEU_ARGENTINA_06'),
			('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITY_NAME_LEU_ARGENTINA_07'),
			('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITY_NAME_LEU_ARGENTINA_08'),
			('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITY_NAME_LEU_ARGENTINA_09'),
			('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITY_NAME_LEU_ARGENTINA_10'),
			('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITY_NAME_LEU_ARGENTINA_11'),
			('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITY_NAME_LEU_ARGENTINA_12'),
			('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITY_NAME_LEU_ARGENTINA_13'),
			('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITY_NAME_LEU_ARGENTINA_14'),
			('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITY_NAME_LEU_ARGENTINA_15'),
			('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITY_NAME_LEU_ARGENTINA_16'),
			('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITY_NAME_LEU_ARGENTINA_17'),
			('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITY_NAME_LEU_ARGENTINA_18'),
			('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITY_NAME_LEU_ARGENTINA_19'),
			('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITY_NAME_LEU_ARGENTINA_20'),
			('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITY_NAME_LEU_ARGENTINA_21'),
			('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITY_NAME_LEU_ARGENTINA_22'),
			('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITY_NAME_LEU_ARGENTINA_23'),
			('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITY_NAME_LEU_ARGENTINA_24'),
			('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITY_NAME_LEU_ARGENTINA_25'),
			('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITY_NAME_LEU_ARGENTINA_26'),
			('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITY_NAME_LEU_ARGENTINA_27'),
			('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITY_NAME_LEU_ARGENTINA_28'),
			('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITY_NAME_LEU_ARGENTINA_29'),
			('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITY_NAME_LEU_ARGENTINA_30'),
			('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITY_NAME_LEU_ARGENTINA_31'),
			('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITY_NAME_LEU_ARGENTINA_32'),
			('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITY_NAME_LEU_ARGENTINA_33'),
			('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITY_NAME_LEU_ARGENTINA_34'),
			('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITY_NAME_LEU_ARGENTINA_35'),
			('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITY_NAME_LEU_ARGENTINA_36'),
			('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITY_NAME_LEU_ARGENTINA_37'),
			('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITY_NAME_LEU_ARGENTINA_38'),
			('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITY_NAME_LEU_ARGENTINA_39');


-------------------------------------
-- CivilizationCitizenNames
-------------------------------------	
INSERT INTO CivilizationCitizenNames	
		(CivilizationType,					CitizenName,								Female,		Modern)
VALUES	('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITIZEN_LEU_ARGENTINA_MALE_1',				0,			0),
		('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITIZEN_LEU_ARGENTINA_MALE_2',				0,			0),
		('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITIZEN_LEU_ARGENTINA_MALE_3',				0,			0),
		('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITIZEN_LEU_ARGENTINA_MALE_4',				0,			0),
		('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITIZEN_LEU_ARGENTINA_MALE_5',				0,			0),
		('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITIZEN_LEU_ARGENTINA_MALE_6',				0,			0),
		('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITIZEN_LEU_ARGENTINA_MALE_7',				0,			0),
		('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITIZEN_LEU_ARGENTINA_MALE_8',				0,			0),
		('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITIZEN_LEU_ARGENTINA_MALE_9',				0,			0),
		('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITIZEN_LEU_ARGENTINA_MALE_10',			0,			0),
		('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITIZEN_LEU_ARGENTINA_FEMALE_1',			1,			0),
		('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITIZEN_LEU_ARGENTINA_FEMALE_2',			1,			0),
		('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITIZEN_LEU_ARGENTINA_FEMALE_3',			1,			0),
		('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITIZEN_LEU_ARGENTINA_FEMALE_4',			1,			0),
		('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITIZEN_LEU_ARGENTINA_FEMALE_5',			1,			0),
		('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITIZEN_LEU_ARGENTINA_FEMALE_6',			1,			0),
		('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITIZEN_LEU_ARGENTINA_FEMALE_7',			1,			0),
		('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITIZEN_LEU_ARGENTINA_FEMALE_8',			1,			0),
		('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITIZEN_LEU_ARGENTINA_FEMALE_9',			1,			0),
		('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITIZEN_LEU_ARGENTINA_FEMALE_10',			1,			0),
		('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITIZEN_LEU_ARGENTINA_MODERN_MALE_1',		0,			1),
		('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITIZEN_LEU_ARGENTINA_MODERN_MALE_2',		0,			1),
		('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITIZEN_LEU_ARGENTINA_MODERN_MALE_3',		0,			1),
		('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITIZEN_LEU_ARGENTINA_MODERN_MALE_4',		0,			1),
		('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITIZEN_LEU_ARGENTINA_MODERN_MALE_5',		0,			1),
		('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITIZEN_LEU_ARGENTINA_MODERN_MALE_6',		0,			1),
		('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITIZEN_LEU_ARGENTINA_MODERN_MALE_7',		0,			1),
		('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITIZEN_LEU_ARGENTINA_MODERN_MALE_8',		0,			1),
		('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITIZEN_LEU_ARGENTINA_MODERN_MALE_9',		0,			1),
		('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITIZEN_LEU_ARGENTINA_MODERN_MALE_10',		0,			1),
		('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITIZEN_LEU_ARGENTINA_MODERN_FEMALE_1',	1,			1),
		('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITIZEN_LEU_ARGENTINA_MODERN_FEMALE_2',	1,			1),
		('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITIZEN_LEU_ARGENTINA_MODERN_FEMALE_3',	1,			1),
		('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITIZEN_LEU_ARGENTINA_MODERN_FEMALE_4',	1,			1),
		('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITIZEN_LEU_ARGENTINA_MODERN_FEMALE_5',	1,			1),
		('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITIZEN_LEU_ARGENTINA_MODERN_FEMALE_6',	1,			1),
		('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITIZEN_LEU_ARGENTINA_MODERN_FEMALE_7',	1,			1),
		('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITIZEN_LEU_ARGENTINA_MODERN_FEMALE_8',	1,			1),
		('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITIZEN_LEU_ARGENTINA_MODERN_FEMALE_9',	1,			1),
		('CIVILIZATION_LEU_ARGENTINA',		'LOC_CITIZEN_LEU_ARGENTINA_MODERN_FEMALE_10',	1,			1);			

-------------------------------------			
-- StartBiasRivers			
-------------------------------------	
INSERT INTO StartBiasRivers	
		(CivilizationType,					Tier)
VALUES	('CIVILIZATION_LEU_ARGENTINA',		6);
-------------------------------------			
-- StartBiasTerrains			
-------------------------------------	
INSERT INTO StartBiasTerrains	
		(CivilizationType,					TerrainType,		Tier)
VALUES	('CIVILIZATION_LEU_ARGENTINA',		'TERRAIN_PLAINS',	5);
-------------------------------------			
-- StartBiasResources			
-------------------------------------	
INSERT INTO StartBiasResources
		(CivilizationType,					ResourceType,		Tier)
VALUES	('CIVILIZATION_LEU_ARGENTINA',		'RESOURCE_HORSES',	2),
		('CIVILIZATION_LEU_ARGENTINA',		'RESOURCE_CATTLE',	3);
-------------------------------------			
-- CivilizationInfo			
-------------------------------------		
INSERT INTO CivilizationInfo	
			(CivilizationType,					Header,						Caption,									SortIndex)	
VALUES		('CIVILIZATION_LEU_ARGENTINA',		'LOC_CIVINFO_LOCATION',		'LOC_CIVINFO_LEU_ARGENTINA_LOCATION',		10),	
			('CIVILIZATION_LEU_ARGENTINA',		'LOC_CIVINFO_SIZE',			'LOC_CIVINFO_LEU_ARGENTINA_SIZE',			20),	
			('CIVILIZATION_LEU_ARGENTINA',		'LOC_CIVINFO_POPULATION',	'LOC_CIVINFO_LEU_ARGENTINA_POPULATION',		30),	
			('CIVILIZATION_LEU_ARGENTINA',		'LOC_CIVINFO_CAPITAL', 		'LOC_CIVINFO_LEU_ARGENTINA_CAPITAL',		40);


--==========================================================================================================================
-- JFD RULE WITH FAITH
--==========================================================================================================================
-- Leader_Titles 
------------------------------------------------------------	
CREATE TABLE IF NOT EXISTS 
	Civilization_Titles (
	CivilizationType  				text 		 		default null,
	GovernmentType					text 	 			default null,
	LeaderTitle						text				default null,
	PolicyType  					text 		 		default null);	
	
INSERT INTO Civilization_Titles
		(CivilizationType, 			GovernmentType, 							PolicyType,				LeaderTitle)
VALUES	('CIVILIZATION_LEU_ARGENTINA',	'GOVERNMENT_CHIEFDOM',						null,					'LOC_GOVERNMENT_JFD_CHIEFDOM_LEADER_TITLE_LEU_ARGENTINA'),				
		('CIVILIZATION_LEU_ARGENTINA',	'GOVERNMENT_JFD_HORDE',						null,					'LOC_GOVERNMENT_JFD_HORDE_LEADER_TITLE_LEU_ARGENTINA'),					
		('CIVILIZATION_LEU_ARGENTINA',	'GOVERNMENT_JFD_POLIS',						null,					'LOC_GOVERNMENT_JFD_POLIS_LEADER_TITLE_LEU_ARGENTINA'),					
		('CIVILIZATION_LEU_ARGENTINA',	'GOVERNMENT_AUTOCRACY',						null,					'LOC_GOVERNMENT_JFD_AUTOCRACY_LEADER_TITLE_LEU_ARGENTINA'),				
		('CIVILIZATION_LEU_ARGENTINA',	'GOVERNMENT_OLIGARCHY',						null,					'LOC_GOVERNMENT_JFD_OLIGARCHY_LEADER_TITLE_LEU_ARGENTINA'),				
		('CIVILIZATION_LEU_ARGENTINA',	'GOVERNMENT_CLASSICAL_REPUBLIC',			null,					'LOC_GOVERNMENT_JFD_CLASSICAL_DEMOCRACY_LEADER_TITLE_LEU_ARGENTINA'),	
		('CIVILIZATION_LEU_ARGENTINA',	'GOVERNMENT_MERCHANT_REPUBLIC',				null,					'LOC_GOVERNMENT_JFD_MERCHANT_REPUBLIC_LEADER_TITLE_LEU_ARGENTINA'),		
		('CIVILIZATION_LEU_ARGENTINA',	'GOVERNMENT_MONARCHY',						null,					'LOC_GOVERNMENT_JFD_MONARCHY_LEADER_TITLE_LEU_ARGENTINA'),				
		('CIVILIZATION_LEU_ARGENTINA',	'GOVERNMENT_JFD_ABSOLUTE_MONARCHY',			null,					'LOC_GOVERNMENT_JFD_MONARCHY_LEADER_TITLE_LEU_ARGENTINA'),				
		('CIVILIZATION_LEU_ARGENTINA',	'GOVERNMENT_JFD_CONSTITUTIONAL_MONARCHY',	null,					'LOC_GOVERNMENT_JFD_MONARCHY_LEADER_TITLE_LEU_ARGENTINA'),				
		('CIVILIZATION_LEU_ARGENTINA',	'GOVERNMENT_JFD_NOBLE_REPUBLIC',			null,					'LOC_GOVERNMENT_JFD_NOBLE_REPUBLIC_LEADER_TITLE_LEU_ARGENTINA'),			
		('CIVILIZATION_LEU_ARGENTINA',	'GOVERNMENT_DEMOCRACY',						null,					'LOC_GOVERNMENT_JFD_LIBERAL_DEMOCRACY_LEADER_TITLE_LEU_ARGENTINA'),		
		('CIVILIZATION_LEU_ARGENTINA',	'GOVERNMENT_COMMUNISM',						null,					'LOC_GOVERNMENT_JFD_PEOPLES_REPUBLIC_LEADER_TITLE_LEU_ARGENTINA'),		
		('CIVILIZATION_LEU_ARGENTINA',	'GOVERNMENT_FASCISM',						null,					'LOC_GOVERNMENT_JFD_MILITARY_GUARDIANSHIP_LEADER_TITLE_LEU_ARGENTINA'),	
		('CIVILIZATION_LEU_ARGENTINA',	null,										'POLICY_JFD_EMPIRE',	'LOC_GOVERNMENT_JFD_EMPIRE_LEADER_TITLE_LEU_ARGENTINA');					
DELETE FROM Civilization_Titles WHERE CivilizationType = 'CIVILIZATION_LEU_ARGENTINA' AND GovernmentType IS NOT null AND GovernmentType NOT IN (SELECT GovernmentType FROM Governments);
DELETE FROM Civilization_Titles WHERE CivilizationType = 'CIVILIZATION_LEU_ARGENTINA' AND PolicyType IS NOT null AND PolicyType NOT IN (SELECT PolicyType FROM Policies);

--==========================================================================================================================
--==========================================================================================================================
